baseURL = 'https://ksbee21.github.io/'
languageCode = 'en-us'
title = '잊혀져 가는 기억을 기록하기 ....'
author = 'KS.KIM'


theme = "blackburn"

copyright = "&copy; 2022. All right reserved."
cononifyurls = true
paginate = 10

enableRobotsTXT = true

[indexes]
  tag = "tags"
  topic = "topics"

[params]
    subtitle = "천천히 ... 그리고 꾸준히 ..."
    brand = "KNMS"
    dateFormat = "2006. 01. 02, 15:04"    
    googleAnalytics = "G-XGZQZNDGGT"
    disqus = ""
    # CSS name for highlight.js
    highlightjs = "androidstudio"
    highlightjs_extra_languages = ["yaml"]
    # Include any custom CSS and/or JS files
    # (relative to /static folder)
    custom_css = ["css/main.css"]
    custom_js = ["js/main.js"]

  [params.piwikAnalytics]
    siteid = 2
    piwikroot = "/"    


[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
 [[menu.main]]
   name = "Contact"
   pre = "<i class='fa fa-phone fa-fw'></i>"
   weight = 4
   url = "/contact/"    

[outputs]
  home = ["HTML","RSS","JSON"]


[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"


